// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// priorUpts
arma::vec priorUpts(arma::mat gridpts, arma::mat obspt, arma::vec radius);
RcppExport SEXP _razimuth_priorUpts(SEXP gridptsSEXP, SEXP obsptSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gridpts(gridptsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type obspt(obsptSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(priorUpts(gridpts, obspt, radius));
    return rcpp_result_gen;
END_RCPP
}
// vhf_cc_mu
arma::vec vhf_cc_mu(arma::vec cp, arma::vec thetalist, arma::mat thetatmp, int distid);
RcppExport SEXP _razimuth_vhf_cc_mu(SEXP cpSEXP, SEXP thetalistSEXP, SEXP thetatmpSEXP, SEXP distidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type cp(cpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetalist(thetalistSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type thetatmp(thetatmpSEXP);
    Rcpp::traits::input_parameter< int >::type distid(distidSEXP);
    rcpp_result_gen = Rcpp::wrap(vhf_cc_mu(cp, thetalist, thetatmp, distid));
    return rcpp_result_gen;
END_RCPP
}
// pmode_cpp
List pmode_cpp(arma::mat x, arma::mat ux);
RcppExport SEXP _razimuth_pmode_cpp(SEXP xSEXP, SEXP uxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ux(uxSEXP);
    rcpp_result_gen = Rcpp::wrap(pmode_cpp(x, ux));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_razimuth_priorUpts", (DL_FUNC) &_razimuth_priorUpts, 3},
    {"_razimuth_vhf_cc_mu", (DL_FUNC) &_razimuth_vhf_cc_mu, 4},
    {"_razimuth_pmode_cpp", (DL_FUNC) &_razimuth_pmode_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_razimuth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
